import React, { createContext, useContext, useMemo, useState } from "react";

const PORTAL_LANGUAGE_STORAGE_KEY = "portal_language";

export const PORTAL_LANGUAGES = [
  { code: "fr", label: "Francais", shortLabel: "FR", flagLabel: "France" },
  { code: "en", label: "English", shortLabel: "EN", flagLabel: "United Kingdom" },
];

const PortalLanguageContext = createContext({
  language: "fr",
  setLanguage: () => {},
  currentLanguage: PORTAL_LANGUAGES[0],
  t: (_key, fallback) => fallback || "",
});

const PORTAL_TRANSLATIONS = {
  "nav.home": "Home",
  "nav.heroBox": "My heroes",
  "nav.soulStones": "Soul stones",
  "nav.demonMonsters": "Demonic monsters",
  "nav.personalBest": "My BP",
  "nav.defenses": "My defenses",
  "nav.gvg": "GVG",
  "nav.runSearch": "Run search",
  "nav.settings": "Settings",
  "nav.guildManagement": "Guild management",
  "nav.adminDefenses": "Defense management",
  "nav.intersaison": "Off-season",
  "nav.runAdd": "Add run",
  "nav.runEdit": "Edit run",
  "nav.templates": "Add hero",
  "nav.guilds": "Guilds",
  "nav.billing": "Licenses",
  "nav.launcher": "Launcher",
  "nav.validation": "Validation",
  "nav.logs": "Logs",
  "nav.playerAccess": "Player access",
  "nav.admin": "Admin",
  "portal.label": "Portal",
  "portal.apiReady": "VPS API ready",
  "language.current": "Current language",
  "login.title": "Dashboard of Realms - Sign in",
  "login.welcome": "Welcome",
  "login.identifier": "Discord ID",
  "login.password": "Password",
  "login.remember": "Remember me",
  "login.forgot": "Forgot password?",
  "login.submit": "Sign in",
  "login.submitting": "Signing in...",
  "login.missingCredentials": "Enter your Discord ID and password.",
  "login.invalidCredentials": "Discord ID or password is incorrect.",
  "login.failed": "Unable to sign in. Try again or contact an admin.",
  "login.showPassword": "Show password",
  "login.hidePassword": "Hide password",
  "login.forgotTitle": "Forgot password",
  "login.forgotHelp": "Enter your Discord ID. We will show the admins you should contact for your guild.",
  "login.forgotIdLabel": "Discord ID",
  "login.forgotIdPlaceholder": "Your Discord ID",
  "login.forgotSearch": "Find my admins",
  "login.forgotSearching": "Searching...",
  "login.forgotMissingId": "Enter your Discord ID first.",
  "login.forgotNotFound": "No Portal account was found for this Discord ID.",
  "login.forgotNoGuild": "This account has no guild assigned. Contact a Paladin admin.",
  "login.forgotResultTitle": "Contact your guild admins",
  "login.forgotResultIntro": "Your account is linked to {guild}. Contact one of these admins to recover access.",
  "login.forgotNoAdmin": "No admin was found for this guild. Contact Darius or a Paladin leader.",
  "login.forgotDiscordId": "Discord ID",
  "login.forgotRole": "Role",
  "home.playerHome": "Player home",
  "home.guild": "Guild",
  "home.role": "Role",
  "home.profile": "Profile",
  "home.notValidated": "Not validated",
  "home.welcome": "Welcome",
  "home.description": "Manage your tools, track your activity and prepare your battles for glory.",
  "home.profileCard": "Player profile",
  "home.heroesCard": "Heroes",
  "home.myProfile.title": "My profile",
  "home.myProfile.description": "Manage your personal information and preferences.",
  "home.heroBox.title": "My heroes",
  "home.heroBox.description": "Open your collection and manage your heroes.",
  "home.soulStones.title": "Soul stones",
  "home.soulStones.description": "Manage and optimize your soul stones.",
  "home.demonMonsters.title": "Demonic monsters",
  "home.demonMonsters.description": "Fight dark forces and tame them.",
  "home.personalBest.title": "My BP",
  "home.personalBest.description": "Check your records and personal performance.",
  "home.defenses.title": "My defenses",
  "home.defenses.description": "Configure and strengthen your defenses.",
  "heroBox.title": "My heroes",
  "heroBox.description": "Collection powered by Supabase, with layers served by the VPS and awakenings linked to champions.",
  "heroBox.statsLabel": "Collection statistics",
  "heroBox.owned": "Owned",
  "heroBox.legendaryAwakenings": "Leg. awakenings",
  "heroBox.legendaryA5": "A5 leg.",
  "heroBox.viewedBox": "Viewed box",
  "heroBox.selectPlayer": "Select a player",
  "heroBox.searchPlayer": "Search player",
  "heroBox.editAllowed": "Editing allowed for this box.",
  "heroBox.readOnly": "Read only: you can view this box, but only your own box or admins can edit it.",
  "heroBox.sync": "Syncing Supabase...",
  "heroBox.searchHero": "Search hero",
  "heroBox.filterHeroes": "Filter heroes",
  "heroBox.filterAll": "All",
  "heroBox.filterOwned": "Owned",
  "heroBox.filterLocked": "Locked",
  "heroBox.filterAwakening5": "Awakening 5",
  "heroBox.rarityFilters": "Rarity filters",
  "heroBox.roleFilters": "Role filters",
  "heroBox.factionFilters": "Faction filters",
  "heroBox.latest": "Latest releases",
  "heroBox.latestTitle": "Show the latest in-game releases",
  "heroBox.bulkSaving": "Updating A5...",
  "heroBox.bulkApply": "Set this filter A5",
  "heroBox.bulkDone": "Filter already A5",
  "heroBox.latestBadge": "Latest in-game releases",
  "heroBox.loadingImages": "Loading thumbnails",
  "heroBox.readOnlyShort": "Read only",
  "heroBox.displayedHeroes": "heroes displayed",
  "heroBox.markOwned": "Mark as owned",
  "heroBox.awakening": "awakening",
  "heroBox.notOwned": "not owned",
  "heroBox.setAwakening": "Set awakening",
  "heroBox.allRoles": "All roles",
  "heroBox.allRolesShort": "All",
  "heroBox.allFactions": "All factions",
  "heroBox.allFactionsShort": "All",
  "heroDetails.eyebrow": "Hero profile",
  "heroDetails.open": "Open hero profile",
  "heroDetails.tags": "Hero information",
  "heroDetails.officialImageReady": "Official Moonton portrait connected to the VPS.",
  "heroDetails.officialImageMissing": "Official Moonton portrait missing for this hero.",
  "heroDetails.inProgressTitle": "Page under construction",
  "heroDetails.inProgressText": "Awakenings, gear and uses by content will be added here step by step.",
  "heroRole.combattant": "Fighter",
  "heroRole.heal": "Healer",
  "heroRole.soigneur": "Healer",
  "heroRole.mage": "Mage",
  "heroRole.tacticien": "Tactician",
  "heroRole.tank": "Tank",
  "heroRole.tireur": "Marksman",
  "heroFaction.arbitre": "Arbiter",
  "heroFaction.cauchemar": "Nightmare",
  "heroFaction.chaotique": "Chaotic",
  "heroFaction.cultiste": "Cultist",
  "heroFaction.esoterique": "Esotericist",
  "heroFaction.infernal": "Infernal",
  "heroFaction.innommable": "Nameless",
  "heroFaction.nordiste": "Northerner",
  "heroFaction.perceur": "Piercer",
  "heroFaction.sentinelle": "Sentinel",
  "rarity.legendary": "Legendary",
  "rarity.epic": "Epic",
  "rarity.rare": "Rare",
  "rarity.ordinary": "Ordinary",
  "rarity.basic": "Basic",
  "gvg.current": "Current GVG",
  "gvg.panel": "Control",
  "gvg.imports": "VPS imports",
  "gvg.adminReserved": "Reserved for admins and leaders",
  "gvg.chooseGuild": "Choose the guild to display.",
  "gvg.selectedGuild": "Selected guild",
  "gvg.changeGuild": "Change guild",
  "gvg.loading": "Loading GVG...",
  "gvgCurrent.bastionNumber": "Stronghold {number}",
  "gvgCurrent.def": "Def",
  "gvgCurrent.repro": "Repro",
  "gvgCurrent.strat": "Strat",
  "gvgCurrent.selectedBastion": "Selected stronghold",
  "gvgCurrent.viewAllDefenses": "View all defenses",
  "gvgCurrent.noDefenseForFilter": "No defense for this filter.",
  "gvgCurrent.slotOpened": "Open",
  "gvgCurrent.slotEmpty": "Empty",
  "gvgCurrent.slotPlaceholder": "Slot",
  "gvgCurrent.fortressTeam": "Keep · Team {team}",
  "gvgCurrent.towerTeam": "Tower {tower} · Team {team}",
  "gvgCurrent.teamOnly": "Team {team}",
  "gvgCurrent.shortTowerTeam": "T{tower} · Team {team}",
  "gvgCurrent.statusReproBy": "Repro by {player}",
  "gvgCurrent.statusRepro": "Repro in progress",
  "gvgCurrent.statusStrat": "Strat available",
  "gvgCurrent.statusToOpen": "To open",
  "gvgCurrent.markAsRepro": "It's repro",
  "gvgCurrent.cancelRepro": "Cancel repro",
  "gvgCurrent.viewRuns": "View available runs",
  "gvgCurrent.noVisibleRun": "No run visible for this account",
  "gvgCurrent.whoCanRepro": "Who can repro",
  "gvgCurrent.markAsOpen": "It's open",
  "gvgCurrent.viewDefenseImage": "View the defense image enlarged",
  "gvgCurrent.enemyGroupTitle": "Group of identical enemy defenses",
  "gvgCurrent.mirrorGroupTitle": "Composition also present on the ally side: avoid early in GVG",
  "gvgCurrent.reproModalTitle": "Repro",
  "gvgCurrent.reproModalHelp": "Complete the missing fields",
  "gvgCurrent.reproOn": "Repro on",
  "gvgCurrent.reproPlayerBp": "Repro k BP",
  "gvgCurrent.reproEnemyBp": "Enemy k BP",
  "gvgCurrent.heroSlot": "Hero {slot}:",
  "gvgCurrent.stuffPlaceholder": "gear: ...",
  "gvgCurrent.artifact": "Artifact",
  "gvgCurrent.saveRepro": "Save repro",
  "gvgCurrent.savedReproTitle": "Saved repro",
  "gvgCurrent.reproSaved": "Repro saved successfully.",
  "gvgCurrent.noReproSaved": "No repro saved.",
  "gvgCurrent.availableStrats": "Available strats",
  "gvgCurrent.noStratFound": "No strat found.",
  "gvgCurrent.stratNumber": "Strat #{number}",
  "gvgCurrent.externalRun": "External run - {guild}",
  "gvgCurrent.video": "Video",
  "gvgCurrent.openVideo": "Open video",
  "gvgCurrent.code": "Code",
  "gvgCurrent.attackCode": "Attack code",
  "gvgCurrent.noAttackCode": "No code",
  "gvgCurrent.instructions": "Instructions",
  "gvgCurrent.noInstructions": "No specific instruction",
  "gvgCurrent.slots": "Slots",
  "gvgCurrent.editRun": "Edit",
  "gvgCurrent.editLimited": "Editing is limited to the editable bank",
  "gvgCurrent.boycottRun": "Boycott",
  "gvgCurrent.deleteRun": "Delete",
  "gvgCurrent.deleteLimited": "Deletion is limited to the editable bank",
  "gvgCurrent.deleteRunConfirm": "Delete strat #{number}?",
  "gvgCurrent.errorMissingStrat": "Run not found.",
  "gvgCurrent.errorBoycottRun": "Unable to boycott: {error}",
  "gvgCurrent.errorDeleteRun": "Unable to delete: {error}",
  "gvgCurrent.whoCanReproDefense": "Who can repro this defense",
  "gvgCurrent.canRepro": "Can repro",
  "gvgCurrent.incomplete": "Incomplete",
  "gvgCurrent.errorNonJson": "Non-JSON response {context} ({status})",
  "gvgCurrent.errorLoad": "GVG loading error: {error}",
  "gvgCurrent.errorRepro": "Repro error: {error}",
  "gvgCurrent.errorReadStrat": "Strat loading error: {error}",
  "gvgCurrent.errorReadRepro": "Repro loading error: {error}",
  "gvgCurrent.errorTemplateRepro": "Repro template error: {error}",
  "gvgCurrent.errorCancelRepro": "Cancel repro error: {error}",
  "gvgCurrent.errorPanelOpen": "Open panel error: {error}",
  "gvgCurrent.errorSaveRepro": "Save repro error: {error}",
  "gvgCurrent.alreadyOpen": "This defense is already open in the panel.",
  "gvgCurrent.sentToPanel": "Defense sent to the panel.",
  "common.loading": "Loading...",
  "common.loadingParenthesis": "(loading...)",
  "common.search": "Search",
  "common.reset": "Reset",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.none": "None",
  "common.empty": "Empty",
  "common.ready": "Ready",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.add": "Add",
  "common.remove": "Remove",
  "common.all": "All",
  "common.position": "Position",
  "common.direction": "Direction",
  "common.hero": "Hero",
  "common.heroes": "Heroes",
  "common.refresh": "Refresh",
  "common.confirm": "Confirm",
  "common.and": "and",
  "common.back": "Back",
  "common.player": "Player",
  "common.member": "Member",
  "common.cluster": "Cluster",
  "common.noPlayer": "No player",
  "common.noPlayerFound": "No player found.",
  "common.noMember": "No member",
  "common.noMemberSelected": "No member selected.",
  "common.searchPlayer": "Search player",
  "common.clusterPlayer": "Cluster player",
  "common.important": "Important",
  "common.entries": "entries",
  "common.filters": "Filters",
  "common.type": "Type",
  "common.allPlural": "All",
  "common.notFilled": "Not filled",
  "common.noImage": "No image",
  "common.image": "Image",
  "common.text": "Text",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.typeAtLeast2": "Type at least 2 letters.",
  "common.adminReserved": "Reserved for administrators.",
  "common.editNotAllowed": "Editing not allowed",
  "common.saving": "Saving...",
  "common.unknownError": "unknown error",
  "soul.tabs.stones": "My stones",
  "soul.tabs.history": "History",
  "soul.tabs.ranking": "Ranking",
  "soul.total": "Total",
  "soul.removeLast": "Remove the latest stone",
  "soul.addStone": "Add a stone",
  "soul.lastReceived": "Last stone received",
  "soul.eyebrow": "Mystic inventory",
  "soul.title": "Soul stones",
  "soul.description": "Manage Lord and Brute stones with player history and cluster ranking.",
  "soul.navigation": "Navigation",
  "soul.navigationHelp": "Stones, history and cluster",
  "soul.clusterPlayer": "Cluster player",
  "soul.importantHelp": "enter the real total: inventory plus stones already used on your heroes.",
  "soul.buttonsHelp": "The + and - buttons add an entry or remove the latest entry of the chosen type.",
  "soul.loading": "Loading soul stones...",
  "soul.lordStone": "Lord stone",
  "soul.bruteStone": "Brute stone",
  "soul.history": "History",
  "soul.noHistory": "No history.",
  "soul.clusterRanking": "Cluster ranking",
  "soul.rankingSort": "Sorted by total, then Lord stones",
  "soul.rankingLoading": "Loading ranking...",
  "soul.noRanking": "No ranking available.",
  "demon.rarity.mythique": "Mythic",
  "demon.rarity.mythic": "Mythic",
  "demon.rarity.legendaire": "Legendary",
  "demon.rarity.legendary": "Legendary",
  "demon.rarity.epique": "Epic",
  "demon.rarity.epic": "Epic",
  "demon.rarity.rare": "Rare",
  "demon.eyebrow": "Demonic library",
  "demon.title": "Demonic monsters",
  "demon.description": "Same flow as the old dashboard: library, rarities, levels and per-player saves.",
  "demon.owned": "Owned",
  "demon.level20": "Level 20",
  "demon.displayed": "Displayed",
  "demon.filtersHelp": "Rarity and active player",
  "demon.levelHelp": "Click the level in the center of a card to enter or correct the monster level.",
  "demon.boxTitle": "Demonic monster box",
  "demon.monstersDisplayed": "monster(s) displayed",
  "demon.searchMonster": "Search monster",
  "demon.libraryLoading": "Loading library...",
  "demon.setLevel": "Set level",
  "demon.levelShort": "Lvl.",
  "demon.selectedMonster": "Selected monster",
  "demon.currentLevel": "Current level",
  "demon.monsterLevel": "Monster level",
  "demon.levelPlaceholder": "Between 0 and 20",
  "defenses.defenseList": "Defense list",
  "defenses.tower": "Tower",
  "defenses.towers": "Towers",
  "defenses.bastion": "Bastion",
  "defenses.bastions": "Bastions",
  "defenses.bubble": "Bubble",
  "defenses.bubbles": "Bubbles",
  "defenses.addDefense": "Add this defense",
  "defenses.removeDefense": "Remove this defense",
  "defenses.clearDefense": "Clear Def",
  "defenses.secondary": "Secondary",
  "adminDefenses.title": "Defense management",
  "adminDefenses.description": "Manage the defenses available in My defenses.",
  "adminDefenses.portalDescription": "Admin management for defenses available in My defenses.",
  "adminDefenses.addDefense": "Add defense",
  "adminDefenses.editDefense": "Edit defense",
  "adminDefenses.visibleDefenses": "visible defenses",
  "adminDefenses.loading": "Loading defenses...",
  "adminDefenses.noDefenseLoaded": "No defense loaded.",
  "adminDefenses.info": "Info",
  "adminDefenses.infoButton": "Info",
  "adminDefenses.defenseInfo": "Defense info",
  "adminDefenses.infoImageAlt": "Defense info",
  "adminDefenses.moreInfo": "info item(s) in the modal",
  "adminDefenses.addTextBlock": "Add text block",
  "adminDefenses.textPlaceholder": "Write your comment here...",
  "adminDefenses.saveText": "Save text",
  "adminDefenses.addFile": "Add file",
  "adminDefenses.pasteImage": "Paste from clipboard",
  "adminDefenses.pasteZoneTitle": "Quick paste",
  "adminDefenses.pasteZoneHelp": "Click here, then press Ctrl+V to directly add the copied image.",
  "adminDefenses.clipboardUnsupported": "Direct clipboard reading is unavailable. Click the paste zone, then press Ctrl+V.",
  "adminDefenses.clipboardNoImage": "No image found in the clipboard.",
  "adminDefenses.clipboardImageAdded": "Image pasted from clipboard.",
  "adminDefenses.fileImageAdded": "Image added.",
  "adminDefenses.imageUploadInProgress": "Image upload in progress...",
  "adminDefenses.imageUploadFailed": "Unable to add this image.",
  "adminDefenses.noBlock": "No block for this defense.",
  "adminDefenses.blockImageAlt": "Defense block",
  "adminDefenses.noInfo": "No information available for this defense.",
  "adminDefenses.heroNameHelp": "Heroes must match the Supabase Name field.",
  "adminDefenses.defenseName": "Defense name",
  "adminDefenses.defenseImage": "Defense image",
  "adminDefenses.globalDefense": "Global defense",
  "adminDefenses.addCondition": "Add condition",
  "adminDefenses.removeCondition": "Remove condition",
  "adminDefenses.noCondition": "No condition",
  "adminDefenses.noFaction": "No faction",
  "adminDefenses.minAwakening": "Min awakening",
  "adminDefenses.deleteBlockConfirm": "Delete this block?",
  "guildManagement.title": "Guild management",
  "guildManagement.description": "Meta defense tracking, preparation statuses, Tower/Bubble/Bastion roles and guild transfers.",
  "guildManagement.players": "players",
  "guildManagement.defenses": "defenses",
  "guildManagement.addMember": "Add member",
  "guildManagement.loading": "Loading guild management...",
  "guildManagement.addMemberHelp": "The player will be added to {guild} with the default member password.",
  "guildManagement.playerName": "Player name",
  "guildManagement.personalForumLink": "Personal forum link",
  "guildManagement.autoCreatePrefix": "Automatic creation: player profile, hero box initialized as not owned, 5 empty BP slots, defense role",
  "guildManagement.status": "status",
  "guildManagement.statusTodo": "To do",
  "guildManagement.statusVerify": "To review",
  "guildManagement.statusValid": "Validated",
  "guildManagement.todo": "To do",
  "guildManagement.adding": "Adding...",
  "guildManagement.transferPlayer": "Transfer player",
  "guildManagement.transferAction": "Transfer",
  "guildManagement.leaveCluster": "Leave cluster",
  "guildManagement.leaveGuild": "Leave guild",
  "guildManagement.leaveClusterConfirm": "Permanently remove {player} from the cluster? This will delete all their data.",
  "guildManagement.leaveGuildConfirm": "Permanently remove {player} from the guild? This will delete all their data.",
  "guildManagement.removingMember": "Removing member...",
  "guildManagement.removing": "Removing...",
  "guildManagement.removeMemberError": "Unable to remove this member.",
  "guildManagement.followup": "My follow-up",
  "guildManagement.memberList": "Member list",
  "guildManagement.def1Def2": "Def1 / Def2",
  "guildManagement.role": "Role",
  "guildManagement.completion": "Completion",
  "guildManagement.score": "Score",
  "guildManagement.transfer": "Transfer",
  "guildManagement.assignmentModalTitle": "Defense position",
  "guildManagement.assignmentType": "Category",
  "guildManagement.assignmentNumber": "Number",
  "guildManagement.assignmentTowerNumber": "Tower number",
  "guildManagement.assignmentZone": "Zone",
  "guildManagement.assignmentBubblePosition": "Bubble position",
  "guildManagement.likeDefense": "Like this defense",
  "guildManagement.dislikeDefense": "Dislike this defense",
  "guildManagement.playerPanelTitle": "Player Discord follow-up",
  "guildManagement.assignedDefenses": "Assigned defenses",
  "guildManagement.personalChatLink": "Personal Discord chat link",
  "guildManagement.discordSendHelp": "The send button sends the defenses by DM to the player and copies the same message into their personal chat when a link is set.",
  "guildManagement.discordMessageLabel": "Discord message to send",
  "guildManagement.discordMessageDraftHelp": "You can edit the info and conditions here: it only customizes the Discord message and does not change the source defenses.",
  "guildManagement.resetDiscordMessage": "Reset",
  "guildManagement.emptyDiscordMessage": "The Discord message cannot be empty.",
  "guildManagement.defenseMissingInfo": "The defense is assigned but its Portal details could not be found.",
  "guildManagement.resetStatuses": "Set all to do",
  "guildManagement.resettingStatusesShort": "Reset...",
  "guildManagement.resettingStatuses": "Resetting statuses...",
  "guildManagement.resetStatusesConfirm": "Set all visible players back to To do?",
  "guildManagement.resetStatusesError": "Unable to reset statuses.",
  "guildManagement.personalChatSaveError": "Unable to save the link.",
  "guildManagement.personalChatSaved": "Chat link saved.",
  "guildManagement.noDefenseToSend": "No defense is assigned to this player.",
  "guildManagement.noDiscordId": "Player Discord ID is missing.",
  "guildManagement.sendingDefenses": "Sending to Discord...",
  "guildManagement.defensesSentDmOnly": "Defenses sent by DM. No usable personal chat was found.",
  "guildManagement.defensesSent": "Defenses sent by DM and in the personal chat.",
  "guildManagement.defensesSendError": "Unable to send: {error}",
  "guildManagement.openPersonalChat": "Open chat",
  "guildManagement.sending": "Sending...",
  "guildManagement.sendDefenses": "Send defenses",
  "gvg.ally": "Ally",
  "gvg.enemy": "Enemy",
  "gvgPanel.guildCode": "Guild code",
  "gvgPanel.startRecord": "Start record",
  "gvgPanel.repairRecord": "Repair record",
  "gvgPanel.calculating": "Calculating...",
  "gvgPanel.calculateGroups": "Calculate groups",
  "gvgPanel.pushToBase": "Push to bank",
  "gvgPanel.vpsRecordTracking": "VPS record tracking",
  "gvgPanel.vpsRecordHelp": "Active plan only: mark defenses as To record, start the record, wait for the completion message, then refresh. GVG reset cleans this guild's VPS videos.",
  "gvgPanel.refreshingRecords": "Refreshing...",
  "gvgPanel.refreshVpsRecords": "Refresh VPS records",
  "gvgPanel.toRecord": "To record",
  "gvgPanel.vpsVideosReceived": "VPS videos received",
  "gvgPanel.stillWaiting": "Still waiting",
  "gvgPanel.enemyDefenses": "Enemy defenses",
  "gvgPanel.allyDefenses": "Ally defenses",
  "gvgPanel.returnToCurrent": "Send back to current GVG",
  "gvgPanel.enemyMirrorGroup": "Group of identical enemy defenses",
  "gvgPanel.crossSideMirrorGroup": "Composition also present between enemy and ally",
  "gvgPanel.toggleRecord": "Toggle to record / not record",
  "gvgPanel.comment": "Comment",
  "gvgPanel.attackCode": "Attack code",
  "gvgPanel.recordStatus": "Record status",
  "gvgPanel.viewRuns": "View runs",
  "gvgPanel.startGvgRecord": "Start a GVG record",
  "gvgPanel.recordPlanGuild": "Guild",
  "gvgPanel.recordPlanHelp": "The plan will be limited to this guild and to defenses marked as To record.",
  "gvgPanel.playerInstructions": "What the player must do",
  "gvgPanel.instructionScope": "Choose Enemies, Allies or Both depending on the requested record.",
  "gvgPanel.instructionLauncher": "Click Open record launcher and accept the Windows authorization.",
  "gvgPanel.instructionNoTouch": "Do not touch the mouse during the record.",
  "gvgPanel.instructionRefresh": "When the launcher announces completion, come back here and click Refresh VPS records.",
  "gvgPanel.enemies": "Enemies",
  "gvgPanel.allies": "Allies",
  "gvgPanel.both": "Both",
  "gvgPanel.defensesToRecord": "defense(s) to record",
  "gvgPanel.creatingRecordSession": "Creating record session on the VPS...",
  "gvgPanel.sessionCreated": "Session created",
  "gvgPanel.defensesInPlan": "defense(s) in plan",
  "gvgPanel.openRecordLauncher": "Open record launcher",
  "gvgPanel.downloadInstall": "Download / install",
  "gvgPanel.recordLauncherHelp": "If nothing opens, install the record launcher once, then click open again. At the end of the record, close the launcher message and click Refresh VPS records in the panel.",
  "gvgPanel.commentPlaceholder": "Type your comment...",
  "gvgPanel.attackCodePlaceholder": "Type the attack code...",
  "gvgPanel.returnQuestionStart": "Do you want to send defense",
  "gvgPanel.returnQuestionEnd": "back to current GVG?",
  "gvgPanel.noRunFound": "No run found",
  "gvgPanel.boycottFor": "Boycott for",
  "gvgPanel.editStrat": "Edit strat",
  "gvgPanel.editLimited": "Editing is limited to the editable bank",
  "gvgPanel.deleteStrat": "Delete strat",
  "gvgPanel.deleteLimited": "Deletion limited to the editable bank",
  "gvgPanel.noAttackCode": "No code",
  "gvgPanel.instructions": "Instructions",
  "gvgPanel.noInstructions": "No specific instruction",
  "gvgPanel.recordStatePush": "Pushed to bank",
  "gvgPanel.recordStatePushTitle": "This defense has been sent to the final bank.",
  "gvgPanel.recordStateYoutubeOk": "YouTube OK",
  "gvgPanel.recordStateYoutubeOkTitle": "The YouTube video is linked to this defense.",
  "gvgPanel.recordStateYoutubeError": "YouTube error",
  "gvgPanel.recordStateYoutubeErrorTitle": "YouTube upload error.",
  "gvgPanel.recordStateYoutubeUploading": "YouTube upload...",
  "gvgPanel.recordStateYoutubeUploadingTitle": "The video is being uploaded to YouTube.",
  "gvgPanel.recordStateYoutubeVpsOk": "YouTube VPS OK",
  "gvgPanel.recordStateYoutubeVpsOkTitle": "The VPS received the YouTube link; refresh to sync Supabase.",
  "gvgPanel.recordStateVpsReceived": "VPS video received",
  "gvgPanel.recordStateVpsReceivedTitle": "Video received by the VPS",
  "gvgPanel.recordStateToRecord": "To record",
  "gvgPanel.recordStateToRecordTitle": "This defense is in the next record plan.",
  "gvgPanel.recordStateNotRecord": "Not record",
  "gvgPanel.recordStateNotRecordTitle": "This defense is open in the panel but not requested for recording.",
  "gvgPanel.recordStateOpen": "To open",
  "gvgPanel.recordStateOpenTitle": "Click the line to open this defense in the panel.",
  "gvgAdmin.title": "GVG admin",
  "gvgAdmin.targetGuild": "Target guild",
  "gvgAdmin.reset": "Reset",
  "gvgAdmin.resetting": "Resetting...",
  "gvgAdmin.vpsJobs": "VPS jobs",
  "gvgAdmin.vpsJobsHelp": "Captures sent by player launchers and processed server-side.",
  "gvgAdmin.hiddenJobs": "out-of-guild job(s) hidden",
  "gvgAdmin.captures": "captures",
  "gvgAdmin.state": "State",
  "gvgAdmin.recoOk": "Reco OK",
  "gvgAdmin.importing": "Importing...",
  "gvgAdmin.importInto": "Import into",
  "gvgAdmin.deleteProbeTitle": "Delete this probe from the server",
  "gvgAdmin.deleting": "Deleting...",
  "gvgAdmin.noJobLoaded": "No job loaded for",
  "gvgAdmin.manualEnemyJson": "Manual enemy JSON import",
  "gvgAdmin.importInProgress": "Import in progress...",
  "gvgAdmin.import": "Import",
  "gvgAdmin.manualImageUpload": "Manual GVG image upload",
  "gvgAdmin.uploading": "Uploading...",
  "gvgAdmin.importIdenticalGroups": "Import identical groups",
  "gvgAdmin.groupJsonPlaceholder": "Paste your group map JSON here",
  "gvgAdmin.importGroups": "Import groups",
  "gvgAdmin.allyMode": "ALLY MODE",
  "gvgAdmin.manualAllyJson": "Manual ally JSON import",
  "gvgAdmin.importingAlly": "Importing ally...",
  "gvgAdmin.importAlly": "Import ALLY",
  "gvgAdmin.unknownAge": "Unknown age",
  "gvgAdmin.expired48h": "Expired +48h",
  "gvgAdmin.valid48h": "Valid -48h",
  "launcher.eyebrow": "GVG capture",
  "launcher.title": "Start GVG capture",
  "launcher.description": "The site opens the launcher installed on the PC, then follows the capture until the result is available in Validation.",
  "launcher.startCapture": "Start GVG capture",
  "launcher.openingShort": "Opening...",
  "launcher.download": "Download / reinstall",
  "launcher.state": "Status",
  "launcher.detected": "Launcher detected",
  "launcher.detecting": "Detecting",
  "launcher.detectedReady": "Launcher detected, capture ready to start.",
  "launcher.notDetected": "Paladin GVG launcher not detected on this PC.",
  "launcher.followError": "Launcher tracking error.",
  "launcher.guildDenied": "Guild not allowed for this session.",
  "launcher.opening": "Opening Paladin GVG launcher...",
  "launcher.createError": "Unable to create launcher session.",
  "launcher.launchError": "Launcher start error.",
  "launcher.readyMessage": "Ready to start a capture session.",
  "launcher.playerSteps": "Player steps",
  "launcher.step": "Step",
  "launcher.step1": "Open Watcher of Realms.",
  "launcher.step2": "Go to the GVG screen.",
  "launcher.step3": "When you are ready, press F9.",
  "launcher.step4": "Do not touch the mouse or keyboard during capture.",
  "launcher.sessionTracking": "Session tracking",
  "launcher.noEvent": "Statuses will appear here as soon as the launcher responds.",
  "launcher.captureProgress": "Capture progress",
  "launcher.installHelp": "Install it once to start captures from the site.",
  "launcher.downloadInstall": "Download and install the launcher",
  "launcher.event.created": "Session created",
  "launcher.event.launcher_started": "Launcher detected",
  "launcher.event.waiting_f9": "Waiting for F9",
  "launcher.event.capture_started": "Capture running",
  "launcher.event.capture_progress": "Capture running",
  "launcher.event.uploading": "Uploading",
  "launcher.event.upload_done": "Upload complete",
  "launcher.event.received_by_vps": "Received by VPS",
  "launcher.event.recognition_processing": "Server recognition",
  "launcher.event.ready": "Result available",
  "launcher.event.error": "Error",
  "playerAccess.title": "Player access",
  "playerAccess.description": "Search player, identifier and temporary reset.",
  "playerAccess.loadPlayersError": "Unable to load players.",
  "playerAccess.resetSuccess": "Temporary password generated. The player must change it on next login.",
  "playerAccess.resetError": "Reset failed.",
  "playerAccess.searchPlaceholder": "Name or identifier",
  "playerAccess.selectPlayer": "Select a player.",
  "playerAccess.identifier": "Identifier",
  "playerAccess.temporaryPassword": "Temporary password",
  "playerAccess.adminConfirmation": "Admin confirmation",
  "playerAccess.yourPassword": "Your password",
  "playerAccess.generating": "Generating...",
  "playerAccess.generate": "Generate",
  "playerAccess.protectedAdmin": "Protected admin account.",
  "logs.eyebrow": "Activity log",
  "logs.title": "Player logs",
  "logs.description": "Search a player to view their latest Portal actions: box, BP, monsters, stones, defenses and GVG.",
  "logs.events": "event(s)",
  "logs.searchPlayer": "Type a player name",
  "logs.actionType": "Action type",
  "logs.viewedProfile": "Viewed profile",
  "logs.loading": "Loading logs...",
  "logs.noLog": "No log found for this filter.",
  "logs.loadError": "Unable to load logs.",
  "logs.actor": "Actor",
  "logs.system": "System",
  "logs.target": "Target",
  "logs.filter.heroBox": "Hero box",
  "logs.filter.heroBoxA5": "A5 box",
  "logs.filter.pbHeroes": "BP heroes",
  "logs.filter.monsters": "Monsters",
  "logs.filter.stonesAdd": "Stones +",
  "logs.filter.stonesRemove": "Stones -",
  "logs.filter.defenseAdd": "Defense +",
  "logs.filter.defenseRemove": "Defense -",
  "logs.filter.gvgImport": "GVG import",
  "logs.filter.gvgJobs": "GVG jobs",
  "logs.filter.playerAccess": "Player access",
  "logs.filter.password": "Password",
  "logs.filter.views": "Views",
  "logs.action.heroBoxUpdate": "Hero box update",
  "logs.action.heroBoxBulkA5": "A5 box update",
  "logs.action.pbUpdate": "BP update",
  "logs.action.pbHeroUpdate": "BP hero update",
  "logs.action.demonMonsterUpdate": "Demonic monster update",
  "logs.action.soulStoneAdd": "Soul stone added",
  "logs.action.soulStoneRemove": "Soul stone removed",
  "logs.action.defenseAssign": "Defense assigned",
  "logs.action.defenseUnassign": "Defense removed",
  "logs.action.guildDefenseAssign": "Defense assigned",
  "logs.action.guildDefenseUnassign": "Defense removed",
  "logs.action.guildAssignmentUpdate": "Defense role update",
  "logs.action.guildStatusUpdate": "Defense status update",
  "logs.action.guildMemberTransfer": "Member transfer",
  "logs.action.guildMemberAttach": "Member attached",
  "logs.action.guildMemberCreate": "Member added",
  "logs.action.guildMemberDelete": "Member removed",
  "logs.action.gvgLauncherStart": "GVG capture",
  "logs.action.gvgValidationImport": "GVG import",
  "logs.action.gvgJobDelete": "GVG job deleted",
  "logs.action.playerPasswordReset": "Player access",
  "logs.action.playerPasswordChange": "Password change",
  "logs.action.portalTabView": "Tab opened",
  "logs.action.adminDefenseCreate": "Defense created",
  "logs.action.adminDefenseUpdate": "Defense updated",
  "logs.action.adminDefenseConditionAdd": "Condition added",
  "logs.action.adminDefenseLocalHide": "Defense hidden",
  "logs.action.adminDefenseDelete": "Defense deleted",
  "logs.action.guildExternalCreate": "External guild created",
  "logs.action.intersaisonCampaignCreate": "Off-season campaign created",
  "logs.action.intersaisonCampaignCancel": "Off-season campaign canceled",
  "logs.action.intersaisonTransfersApply": "Off-season transfers applied",
  "logs.entity.tab": "Tab",
  "logs.entity.champion": "Hero",
  "logs.entity.pb": "BP",
  "logs.entity.demonicMonster": "Monster",
  "logs.entity.soulStone": "Soul stone",
  "logs.entity.defense": "Defense",
  "logs.entity.gvg": "GVG",
  "logs.entity.member": "Member",
  "logs.entity.guild": "Guild",
  "logs.entity.guildMembers": "Players",
  "logs.event.unknown": "Event",
  "logs.event.portalTabView": "{actor} opened {tab}",
  "logs.event.heroBoxUpdate": "{target} updated {hero}: A{from} -> A{to}",
  "logs.event.heroBoxBulkA5": "{target} set {count} {rarity} heroes to A5",
  "logs.event.pbHeroUpdate": "{target} changed BP hero {slot}: {from} -> {to}",
  "logs.event.pbUpdate": "{target} updated BP {slot}",
  "logs.event.demonMonsterUpdate": "{target} updated {monster}: level {from} -> {to}",
  "logs.event.soulStoneAdd": "{target} added a {type} soul stone",
  "logs.event.soulStoneRemove": "{target} removed a {type} soul stone",
  "logs.event.defenseAssign": "{target} received defense {slot}: {defense}",
  "logs.event.defenseUnassign": "{target} removed defense {slot}",
  "logs.event.gvgLauncherStart": "{actor} launched a GVG capture {guild} ({side})",
  "logs.event.gvgValidationImport": "{actor} imported {count} GVG defenses into {guild}",
  "logs.event.gvgJobDelete": "{actor} deleted a GVG job {guild} / {job}",
  "logs.event.playerPasswordReset": "{actor} generated a temporary password for {target}",
  "logs.event.playerPasswordChange": "{actor} changed their password",
  "logs.event.guildMemberDelete": "{actor} removed {target} from {guild}",
  "settings.title": "Settings",
  "settings.description": "Portal session management.",
  "settings.connectedAccount": "Connected account",
  "settings.logoutAction": "Log out",
  "run.search.title": "Run search",
  "run.add.title": "Add run",
  "run.edit.title": "Edit run",
  "run.helper": "Click up to 5 squares, then enter hero and direction.",
  "run.mapReference": "Reference",
  "run.rows": "rows",
  "run.columns": "columns",
  "run.clickGrid": "Click a square in the grid.",
  "run.startTyping": "Start typing...",
  "run.emptyHero": "(hero)",
  "run.emptyDirection": "(dir)",
  "run.editor": "Edit",
  "run.currentSelection": "Current selection",
  "run.results": "Results",
  "run.noResult": "No result displayed.",
  "run.searching": "Searching...",
  "run.selectedMap": "Map",
  "run.idPlaceholder": "Run ID",
  "run.load": "Load",
  "run.update": "Update",
  "run.updating": "Updating...",
  "run.saving": "Saving...",
  "run.deleting": "Deleting...",
  "run.delete": "Delete",
  "run.info": "Run information",
  "run.youtubeLink": "YouTube link",
  "run.attackCode": "Attack code",
  "run.comment": "Comment",
  "run.scopeNoticeAdd": "The run will be saved in the connected space's bank.",
  "run.scopeNoticeEdit": "Loading, editing and deleting are limited to the connected space's bank.",
  "run.includeBoycotted": "Include boycotted",
  "run.showingBoycotted": "Boycotted visible",
  "run.boycottOn": "Boycotted run",
  "run.boycottOff": "Active run",
  "run.boycottHelp": "A boycotted run remains available in manual search, but no longer marks a defense as strat in current GVG.",
  "run.boycottBadge": "Boycotted",
  "run.boycottForGuild": "Boycott",
  "run.reactivateForGuild": "Reactivate",
  "run.botSearch": "Bot command search",
  "run.botSearchHelp": "Paste the command generated by their bot, then refine it if needed.",
  "run.launchSearch": "Start search",
  "pb.title": "My BP",
  "pb.kicker": "BP spreadsheet",
  "pb.description": "Ranking of the best BP scores, affis, top 1, top 3 and top 5 in the guild.",
  "pb.players": "Players",
  "pb.myTop1": "My Top 1",
  "pb.averageTop3": "Average Top 3",
  "pb.ranking": "BP ranking",
  "pb.rowHelp": "Click a row for details, click an affi to edit.",
  "pb.sort": "Sort",
  "pb.name": "Name",
  "pb.date": "Date",
  "pb.loading": "Loading BP...",
  "pb.detail": "BP detail",
  "pb.raw": "Raw BP",
  "pb.calculated": "Calculated",
  "pb.noHero": "No hero",
  "pb.editTitle": "Edit BP",
  "pb.rawPlaceholder": "Ex: 138485",
  "pb.slotAwakening": "Awakening used for this BP",
  "pb.boxAwakening": "Box",
  "pb.slotAwakeningHelp": "Box keeps the awakening from My heroes. A0-A5 overrides this affi only.",
  "defenses.title": "My defenses",
  "defenses.loading": "Loading your defenses...",
  "defenses.playerSpace": "Player space",
  "defenses.description": "Choose your two defenses and check whether your current box can play them.",
  "defenses.maxScore": "Max score",
  "defenses.noProfile": "No player profile found for this session.",
  "defenses.openEdit": "editing open",
  "defenses.player": "Player",
  "defenses.noPlayer": "No player found.",
  "defenses.choose": "Choose a defense",
  "defenses.search": "Search defense...",
  "defenses.duplicates": "Hero duplicates are flagged before assignment.",
  "defenses.noDuplicate": "No hero duplicate",
  "defenses.duplicate": "Duplicate",
  "defenses.defense": "Defense",
  "defenses.noneSelected": "No defense selected",
  "defenses.selectBelow": "Select a defense from the list below to fill this slot.",
  "defenses.info": "Defense info",
  "defenses.heroesAwakenings": "Heroes / Awakenings",
  "defenses.missingHeroes": "Missing heroes",
  "defenses.conditions": "Conditions",
  "defenses.awakeningScore": "Awakening score",
  "defenses.noImage": "No image",
  "validation.title": "GVG recognition validation",
  "validation.targetGuild": "Target guild",
  "validation.scopeHelp": "This screen only shows jobs from the selected guild.",
  "validation.loadJobs": "Load jobs",
  "validation.loadingJobs": "Loading...",
  "validation.jobs": "Available jobs",
  "validation.noHiddenJob": "No hidden out-of-guild job.",
  "validation.noJob": "No job",
  "validation.loaded": "loaded.",
  "validation.control": "Defense check",
  "validation.selectedDefense": "Selected defense",
  "validation.selectJob": "Select a job",
  "validation.selectJobHelp": "Load VPS jobs, pick a completed recognition, then check all 48 defenses before import.",
  "validation.payloadLoading": "Loading payload...",
  "validation.noImage": "No image available.",
  "validation.recognizedComp": "Recognized composition",
  "validation.compHelp": "5 slots required. Editing a line puts the defense back into pending validation.",
  "validation.validateOne": "Validate this defense",
  "validation.validateAll": "Validate all",
  "validation.import": "Import",
  "validation.importing": "Importing...",
  "validation.complete": "Complete",
  "validation.toFill": "To fill",
  "validation.heroName": "Hero name",
  "validation.noPayloadItem": "No item in this payload.",
  "settings.logout": "Logout",
};

function translate(language, key, fallback) {
  if (language !== "en") return fallback || key;
  return PORTAL_TRANSLATIONS[key] || fallback || key;
}

function readStoredLanguage() {
  if (typeof window === "undefined") return "fr";

  try {
    const storedLanguage = window.localStorage.getItem(PORTAL_LANGUAGE_STORAGE_KEY);
    return PORTAL_LANGUAGES.some((language) => language.code === storedLanguage) ? storedLanguage : "fr";
  } catch {
    return "fr";
  }
}

export function PortalLanguageProvider({ children }) {
  const [language, setLanguageState] = useState(readStoredLanguage);

  function setLanguage(nextLanguage) {
    const normalizedLanguage = PORTAL_LANGUAGES.some((item) => item.code === nextLanguage) ? nextLanguage : "fr";
    setLanguageState(normalizedLanguage);

    if (typeof window !== "undefined") {
      try {
        window.localStorage.setItem(PORTAL_LANGUAGE_STORAGE_KEY, normalizedLanguage);
      } catch {
        // Local storage can be unavailable in private or embedded contexts.
      }
    }
  }

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      currentLanguage: PORTAL_LANGUAGES.find((item) => item.code === language) || PORTAL_LANGUAGES[0],
      t: (key, fallback) => translate(language, key, fallback),
    }),
    [language],
  );

  return <PortalLanguageContext.Provider value={value}>{children}</PortalLanguageContext.Provider>;
}

export function usePortalLanguage() {
  return useContext(PortalLanguageContext);
}
